#!/usr/bin/env bash

## Run blt setup commands to prepare your local site for
## development.
##
## Usage: fin init

# Abort if anything fails
set -e
#-------------------------- Settings --------------------------------

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

bye(){
    echo "There was an error with $1."

    exit 1
}

#-------------------------- END: Helper Functions --------------------------------

#-------------------------- Execution --------------------------------

# Copy over config files.
cp "$PROJECT_ROOT/.docksal/config_files/example.local.settings.php" "$DOCROOT_PATH/sites/settings/settings.local.php" || bye "local settings file"
cp "$PROJECT_ROOT/simplesamlphp/config/default.local.config.php" "$PROJECT_ROOT/simplesamlphp/config/local.config.php" || bye "simple SAML"

# Updating the scripts with Docksal's domain name in config files.
sed -i.bak "s/example/${VIRTUAL_HOST}/g" "$PROJECT_ROOT/.docksal/config_files/example.local.blt.yml" || bye "Streaming editor: changing config files with"
cp "$PROJECT_ROOT/.docksal/config_files/example.local.blt.yml" "$PROJECT_ROOT/blt/local.blt.yml" || bye "copying local blt"
mv $PROJECT_ROOT/.docksal/config_files/example.local.blt.yml.bak $PROJECT_ROOT/.docksal/config_files/example.local.blt.yml #Because BSD/Mac makes you create a copy.

# Initialize stack
 fin project start

# Install project requirements
fin exec composer clear-cache
fin exec COMPOSER_PROCESS_TIMEOUT=2000
fin exec COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-source
#fin exec composer run-script blt-alias

# Set up blt
cd $DOCROOT_PATH
fin blt blt:init:settings -n
fin blt drupal:install -n
fin blt source:build:simplesamlphp-config

echo
echo -en "${green_bg} DONE! ${NC}"
echo
echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
