#!/usr/bin/env bash

#
#
# usage: fin saml-init

echo "Commencing setting up simplesaml for local dev."
echo

#rsycing necessary saml files.
rsync -av simplesamlphp vendor/simplesamlphp
rsync -av .docksal/config_files/saml.local.config.php vendor/simplesamlphp/simplesamlphp/config/local.config.php
rsync -av .docksal/config_files/local.authsources.php vendor/simplesamlphp/simplesamlphp/config/local.authsources.php
rsync -av keys/saml* vendor/simplesamlphp/simplesamlphp/cert
